In [1]:
import numpy as np

In [2]:
list_= ['1','2','3','4','5']

In [3]:
array_list = np.array(object =list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
array_list.ndim

1

In [6]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [7]:
# Array_list is not a defined data type in Python. Assuming that array_list refers to a list containing arrays, 
# both list_ and array_list would be of the same data type, which is a list for example

In [16]:
import numpy as np

# Define a Python list
list_ = ['1','2','3','4','5']

# Define a list containing NumPy arrays
array_list1 = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

# Print the data types of both variables
print(type(list_))      # Output: <class 'list'>
print(type(array_list1)) # Output: <class 'list'>


<class 'list'>
<class 'list'>


In [9]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [10]:
import numpy as np

# Define a Python list
list_ = ['1','2','3','4','5']

# Define a list containing NumPy arrays
array_list 

# Print the data type of each element in list_
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
for array in array_list:
    for element in array:
        print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
# Q3. Considering the following changes in the variable, array_list:

In [12]:
array_list = np.array(object = list_, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [17]:
for i in array_list:
    print(type(array_list))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [30]:
num_array.shape

(2, 3)

In [31]:
num_array.size

6

In [ ]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.

In [ ]:
 arr =np.zeros((3,3))

In [27]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# Create an identity matrix of shape (5,5) using numpy functions?

In [34]:
arr =np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])